### ISSUE TITLE
Implementar restrições de acesso

### ISSUE THREAD

**Issue by zevatron** [MonitoriaSI/MonitoriaSI#34]
* Apenas o "Coordenador" realizar o CRUD
  1. Disciplinas
  1. Semestres
  1. Turmas
  1. Pessoas
---
* Aluno
  1. new Pessoa (ele próprio)
  1. listar turmas
  1. exibir turma
  1. listar eventos da turma
  1. acessar evento da turma
---
* Monitor 
  1. CRUD Eventos da turma em que ele é monitor

**Comment by talithamedeiros** [comment]
Faltando restrição em eventos.
