### ISSUE TITLE
RF17 - Permitir criar apenas uma turma por disciplina por semestre

### ISSUE THREAD

**Issue by talithamedeiros** [MonitoriaSI/MonitoriaSI#78]
As turmas contém Disciplina e Semestre. Deverá ser implementada restrição para que não haja duas ou mais turmas com mesma disciplina e semestre.
**Dificuldade 2**
Prioridade: [X] Essencial [ ] Importante [ ] Desejável

**Comment by aluisiolins** [comment]
Escolhido - Aluisio - Vamos Trabalhar
