### ISSUE TITLE
RF20 - Mostrar total de horas de monitorias realizadas

### ISSUE THREAD

**Issue by talithamedeiros** [MonitoriaSI/MonitoriaSI#84]
Mostrar os dias de monitorias realizadas na seção de relatório para o coordenador. Ordenadas pelo dia.

**Dificuldade 4**
Prioridade: [ ] Essencial [ ] Importante [X] Desejável

**Comment by aluisiolins** [comment]
Escolhido - Aluisio - Vamos Trabalhar
